-- ============================================================================
-- OrbitoShop baseline schema — built from your real `supabase db dump` /
-- pg_dump output (production-schema.sql), not guesswork. Safe to trust.
-- ============================================================================
-- Usage for a brand-new client project:
--   1. supabase link --project-ref <new-project-ref>
--   2. Put this file in supabase/migrations/<timestamp>_baseline.sql
--   3. supabase db push
-- ============================================================================

-- ── employees ───────────────────────────────────────────────────────────────
create table public.employees (
  id        integer generated by default as identity primary key,
  name      text not null,
  pin_code  text,
  role      text default 'Cashier',
  status    text default 'Active',
  email     text,
  password  text
);
alter table public.employees enable row level security;
create policy "allow all" on public.employees using (true) with check (true);

-- ── shop_config (singleton row, id = 1) ─────────────────────────────────────
create table public.shop_config (
  id                         integer primary key default 1,
  shop_name                  text default 'FixPoint Mobile Care',
  shop_address               text default '',
  shop_phone                 text default '',
  shop_logo                  text default '',
  shop_description           text default '',
  primary_color              text default '#126c5b',
  secondary_color            text default '#e9b949',
  currency                   text default 'Rs.',
  tax_rate                   numeric default 0,
  strict_login_mode          boolean default false,
  discount_pin_required      boolean default true,
  partial_udhar_allowed      boolean default true,
  terms_text                 text default 'Warranty: 30 days on parts replaced.',
  repair_module_enabled      boolean default true,
  inventory_module_enabled   boolean default false,
  technician_module_enabled  boolean default true,
  suspended                  boolean default false,
  platform_client_id         integer,
  platform_url               text,
  platform_anon              text,
  billing_model               text default 'fixed',
  per_receipt_rate            numeric default 0,
  override_pin                 text default '1234',
  per_ticket_rate               numeric default 10,
  per_item_rate                  numeric default 1,
  owner_email                    text,
  owner_password                  text,
  workshop_enabled                 boolean default false,
  live_tracking_enabled            boolean default false,
  ems_enabled                      boolean default false,
  ems_track_breaks                 boolean default false
);
alter table public.shop_config enable row level security;
create policy "allow all" on public.shop_config using (true) with check (true);
insert into public.shop_config (id) values (1) on conflict (id) do nothing;

-- ── inventory ────────────────────────────────────────────────────────────────
create table public.inventory (
  id          integer generated by default as identity primary key,
  name        text not null,
  sku         text default '',
  category    text default 'General',
  price       numeric default 0,
  cost        numeric default 0,
  qty         integer default 0,
  min_qty     integer default 0,
  created_at  timestamptz default now()
);
alter table public.inventory enable row level security;
create policy "allow all" on public.inventory using (true) with check (true);

-- ── quick_items ──────────────────────────────────────────────────────────────
-- prices is jsonb: legacy rows may be a plain array of numbers, newer rows are
-- an array of {name, price} objects (name = optional brand/variant label).
create table public.quick_items (
  id          integer generated by default as identity primary key,
  name        text not null,
  prices      jsonb default '[]'::jsonb,
  sort_order  integer default 0,
  created_at  timestamp default now()
);
-- RLS is OFF on this table in production (confirmed via pg_dump). See the
-- hardening note at the bottom of this file before deciding whether to
-- replicate that for a new client.

-- ── repair_components ────────────────────────────────────────────────────────
create table public.repair_components (
  id          integer generated by default as identity primary key,
  name        text not null,
  sort_order  integer default 0,
  created_at  timestamp default now()
);
-- RLS OFF — see note at bottom.

-- ── tickets ──────────────────────────────────────────────────────────────────
create table public.tickets (
  id                    bigint generated always as identity primary key,
  ticket_number         text unique,
  customer_name         text,
  customer_phone        text,
  device_brand          text,
  device_model          text,
  imei                  text,
  components_noted      jsonb default '[]'::jsonb,
  estimated_quote       numeric default 0,
  advance_payment       numeric default 0,
  advance_method        text default '',
  status                text default 'Pending',
  technician_note       text default '',
  decline_reason        text default '',
  created_by            text default '',
  created_at            timestamptz default now(),
  settled_at            timestamptz,
  update_note           text,
  actual_quote          numeric default 0,
  parts_used            jsonb default '[]'::jsonb,
  labour_cost           numeric default 0,
  final_price_override  numeric,
  amount_paid           numeric default 0,
  balance_due           numeric default 0,
  payment_history       jsonb default '[]'::jsonb,
  is_locked             boolean default false,
  invoice_number        text,
  final_total           numeric default 0,
  placed_at             timestamp,
  collected_at          timestamp,
  parent_ticket_id      bigint references public.tickets(id)
);
alter table public.tickets enable row level security;
create policy "allow all" on public.tickets using (true) with check (true);

-- ── sales ────────────────────────────────────────────────────────────────────
-- items_sold entries: {name, variant_name, qty, original_price, sold_price, discount, reason}
create table public.sales (
  id               bigint generated always as identity primary key,
  ticket_id        bigint references public.tickets(id),
  customer_name    text default '',
  items_sold       jsonb default '[]'::jsonb,
  labour_cost      numeric default 0,
  discount         numeric default 0,
  discount_reason  text default '',
  tax              numeric default 0,
  total_bill       numeric default 0,
  payment_method   text default 'Cash',
  employee_id      integer references public.employees(id),
  employee_name    text default '',
  created_at       timestamptz default now(),
  cash_tendered    numeric default 0,
  change_given     numeric default 0
);
alter table public.sales enable row level security;
create policy "allow all" on public.sales using (true) with check (true);

-- ── udhar (store credit / partial payment tracking) ─────────────────────────
create table public.udhar (
  id               integer generated by default as identity primary key,
  sale_id          bigint references public.sales(id),
  customer_name    text,
  customer_phone   text,
  total_amount     numeric default 0,
  amount_paid      numeric default 0,
  balance_due      numeric default 0,
  payment_history  jsonb default '[]'::jsonb,
  status           text default 'Outstanding',
  created_at       timestamptz default now(),
  settled_at       timestamptz
);
alter table public.udhar enable row level security;
create policy "allow all" on public.udhar using (true) with check (true);

-- ── returns ──────────────────────────────────────────────────────────────────
create table public.returns (
  id                integer generated by default as identity primary key,
  original_sale_id  bigint references public.sales(id),
  returned_items    jsonb default '[]'::jsonb,
  refund_amount     numeric default 0,
  processed_by      integer references public.employees(id),
  notes             text default '',
  created_at        timestamptz default now()
);
alter table public.returns enable row level security;
create policy "allow all" on public.returns using (true) with check (true);

-- ── active_sessions ──────────────────────────────────────────────────────────
-- employee_id is UNIQUE — one active session slot per employee (used to boot
-- older logins when the same employee signs in elsewhere).
create table public.active_sessions (
  id           bigint generated always as identity primary key,
  employee_id  text not null unique,
  session_key  text not null,
  created_at   timestamptz default now()
);
alter table public.active_sessions enable row level security;
create policy anon_access on public.active_sessions using (true) with check (true);

-- ── attendance ───────────────────────────────────────────────────────────────
create table public.attendance (
  id              integer generated by default as identity primary key,
  employee_id     integer references public.employees(id),
  clock_in        timestamp not null default now(),
  clock_out       timestamp,
  break_minutes   integer default 0,
  date            date not null default current_date,
  notes           text default '',
  created_at      timestamp default now()
);
-- RLS OFF — see note at bottom.

-- ── leaves ───────────────────────────────────────────────────────────────────
create table public.leaves (
  id             integer generated by default as identity primary key,
  employee_id    integer references public.employees(id),
  leave_type     text not null default 'Casual',
  from_date      date not null,
  to_date        date not null,
  reason         text default '',
  status         text not null default 'Pending',
  reviewed_by    integer references public.employees(id),
  reviewed_at    timestamp,
  created_at     timestamp default now()
);
-- RLS OFF — see note at bottom.

-- ── salary_config ────────────────────────────────────────────────────────────
-- employee_id is UNIQUE — one salary config row per employee.
create table public.salary_config (
  id               integer generated by default as identity primary key,
  employee_id      integer unique references public.employees(id),
  salary_type      text not null default 'Monthly',
  rate             numeric not null default 0,
  effective_from   date default current_date,
  created_at       timestamp default now()
);
-- RLS OFF — see note at bottom.

-- ── salary_slips ─────────────────────────────────────────────────────────────
-- (employee_id, month, year) is UNIQUE — one slip per employee per month.
create table public.salary_slips (
  id               integer generated by default as identity primary key,
  employee_id      integer references public.employees(id),
  month            integer not null,
  year             integer not null,
  days_in_month    integer not null,
  days_present     integer not null default 0,
  days_absent      integer not null default 0,
  leaves_approved  integer not null default 0,
  salary_type      text not null,
  rate             numeric not null,
  gross_salary     numeric not null default 0,
  deductions       numeric not null default 0,
  net_salary       numeric not null default 0,
  notes            text default '',
  generated_by     integer references public.employees(id),
  generated_at     timestamp default now(),
  unique (employee_id, month, year)
);
-- RLS OFF — see note at bottom.

-- ── password_reset_requests ───────────────────────────────────────────────────
create table public.password_reset_requests (
  id             bigint generated always as identity primary key,
  email          text not null,
  status         text not null default 'Pending',
  requested_at   timestamptz default now(),
  resolved_at    timestamptz,
  resolved_by    text
);
alter table public.password_reset_requests enable row level security;
create policy "anon full access" on public.password_reset_requests using (true) with check (true);

-- ============================================================================
-- FINDINGS FROM YOUR REAL PRODUCTION SCHEMA
-- ============================================================================
-- 1. RLS GAP (confirmed, not guessed this time): six tables have RLS fully
--    OFF — attendance, leaves, quick_items, repair_components, salary_config,
--    salary_slips. Since the app only ever uses the anon key client-side,
--    this has the same practical effect as an "allow all" policy today, so
--    nothing is currently more exposed than your other tables — but it's
--    inconsistent, and if you ever tighten policies on the other 9 tables
--    later, these 6 would silently stay wide open. Recommended for new
--    deployments (uncomment to apply):
--
--      alter table public.attendance enable row level security;
--      create policy "allow all" on public.attendance using (true) with check (true);
--      alter table public.leaves enable row level security;
--      create policy "allow all" on public.leaves using (true) with check (true);
--      alter table public.quick_items enable row level security;
--      create policy "allow all" on public.quick_items using (true) with check (true);
--      alter table public.repair_components enable row level security;
--      create policy "allow all" on public.repair_components using (true) with check (true);
--      alter table public.salary_config enable row level security;
--      create policy "allow all" on public.salary_config using (true) with check (true);
--      alter table public.salary_slips enable row level security;
--      create policy "allow all" on public.salary_slips using (true) with check (true);
--
-- 2. NO CUSTOM INDEXES exist anywhere beyond primary keys and the unique
--    constraints above. Fine at low volume; worth adding later on columns
--    you filter/sort by constantly, e.g.:
--      create index idx_tickets_status on public.tickets(status);
--      create index idx_tickets_created_at on public.tickets(created_at desc);
--      create index idx_sales_created_at on public.sales(created_at desc);
--      create index idx_attendance_employee_date on public.attendance(employee_id, date);
--
-- 3. REDUNDANT / DEAD COLUMN: employees.pin_code exists but nothing in the
--    app code reads it (confirmed earlier — login is email+password only).
--    Not urgent to drop, but if you want to clean it up on a NEW client's
--    db before go-live:
--      alter table public.employees drop column pin_code;
--    (Leave it alone on the existing production db unless you're sure
--    nothing external depends on it.)
--
-- 4. No tables were found to be fully redundant/unused — every table in the
--    dump is referenced somewhere in the app code.
-- ============================================================================